services:
  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://user:password@db:5432/codegolf
    networks:
      - golf
      - proxy

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codegolf
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - golf

volumes:
  db_data:

networks:
  golf:
  proxy:
    external: true
